### ISSUE TITLE
Login e Cadastro

### ISSUE THREAD

**Issue by AndreLFN** [tarmont/personal-guide#14]
# Sistema de Login e Cadastro

## Login e cadastro no site
- Criação das telas de Login e cadastro pelo site.
- Criação do banco de contas

## Login e cadastro por API (Google, Facebook, etc.)
- Criação do Botão de uso da API.
- Consertar o bug de conexão segura.

**Comment by tarmont** [comment]
Uma forma de integrar o devise do rails com o react:
https://blog.usejournal.com/devise-with-react-webpacker-and-rails-dacbf9ae0233
(Se não fosse essa questão da integração do react, essa parte já estaria pronta, de forma funcional)

A gente já está usando o Devise, que criou o modelo ("banco") e as rotas que já estavam funcionando. Quanto a integração com Facebook e afins, o melhor é usar apenas a conta do github mesmo.
